config/routes.rb
Automation::Application.routes.draw do

  get "policy/index"

  get "ad/index"

  get "messagepool/seq"

  get "test_api/index"

  get "playpolicy/index"

  get "playpolicy/show"

  get "playpolicy/new"

  resources :demands

  get "filedb/index"

  get "file_db/index"

  get "demands/index"

  get "interfaces/index"

  get "playlog/index"

  get "monitor/show"

  get "app_info/index"

  get "ds/show"
  resources :interfaces
  resources :params

  match ':controller(/:action(/:id))(.:format)'
  root :to => 'builder#index'
end

app/models/demand.rb
class Demand < ActiveRecord::Base
  attr_accessible :host, :interface_id, :title
  validates_presence_of :host, :title
end

app/controllers/demands_controller.rb
#coding:utf-8
require File.expand_path("../../../lib/json/json_util",__FILE__)

class DemandsController < ApplicationController
  # GET /demands
  # GET /demands.json
  def index
    @demands = Demand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @demands }
    end
  end

  # GET /demands/1
  # GET /demands/1.json
  def show
    @demand = Demand.find(params[:id])
    @all_params = []
    all_params = Param.find_all_by_demand_id(params[:id])
    all_params.each do |p|
      @all_params << p.name if p.kind == 0
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @demand }
    end
  end

  # GET /demands/new
  # GET /demands/new.json
  def new
    @demand = Demand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @demand }
    end
  end

  # GET /demands/1/edit
  def edit
    @demand = Demand.find(params[:id])
  end

  # POST /demands
  # POST /demands.json
  def create
    @demand = params[:demand]
    @interface = params[:interface]
    respond_to do |format|
     begin
       d_save = init_by_demand(@demand)
       i_save = init_by_param(d_save[0].id, d_save[1].id, @demand, @interface) 
       format.html{redirect_to d_save[0]}
     rescue
       flash[:notice] = "save fail,try again!" 
       format.html{render :new}
     end
    end
  end

  # PUT /demands/1
  # PUT /demands/1.json
  def update
    respond_to do |format|
     begin
      @result = get_result
      format.html { render :action => "edit", :id => params[:id] }
     rescue
      flash[:notice] = "select fail,try again!"
      format.html { redirect_to :action => "show", :id => params[:id] }
     end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    @demand = Demand.find(params[:id])
    @demand.destroy
    
    pas = Param.find_all_by_demand_id(params[:id])
    pas.each do |p|
      p.destroy
      i = Interface.find(p.interface_id)
      i.destroy unless i.nil?
    end

    respond_to do |format|
      format.html { redirect_to demands_url }
      format.json { head :no_content }
    end
  end

  private 
    #根据demand信息创建对应的接口
    def init_by_demand demand
      return if demand.nil? || demand.empty?
      #初始化demand接口并保存
      type, children = 0, 0
      interface = Interface.new
      demand.each do |d|
        if d[":host"]
          interface.host = d[":host"].strip
          interface.param = d[":param"].strip
          interface.result = d[":result"].strip
          type = d[":type"].to_i
          children = d[":parent"].to_i
        else
          interface.param += " #{d[':param'].strip}"
        end
      end
      interface.save! 
      #初始化demand对象并保存
      demand = Demand.new
      demand.interface_id = interface.id
      demand.title = params[:title]
      demand.host = interface.host
      demand.save!
      d, i = demand,interface
    end
    
    #根据参数信息创建对应的接口
    def init_by_param(did, iid, demand, param)
      inter_hash, child_hash = [], []
      if param
        #初始化接口并保存
        param.each do |p|
          interface = Interface.new
          interface.host = p[":host"].strip
          interface.param = p[":param"].strip
          interface.result = p[":result"].strip
          interface.save!
          inter_hash << interface.param.to_s
          inter_hash << interface.id.to_i
          child_hash << p[":parent"].to_s
          child_hash << interface.id
        end
      end
      inter_hash = Hash[*inter_hash]
      child_hash = Hash[*child_hash]
      #初始化demand参数对象并保存
      demand.each do |d|
        pa = Param.new
        pa.demand_id = did
        pa.interface_id = iid
        pa.name = d[":param"]
        pa.kind = d[":type"]
        pa.children_interface_id = child_hash["#{d[':param']}"].to_i
        pa.save!
      end
      if param
        #初始化interface参数对象并保存
        param.each do |d|
          pa = Param.new
          pa.demand_id = did
          pa.interface_id = inter_hash["#{d[':param']}"]
          pa.name = d[":param"]
          pa.kind = d[":type"]
          pa.children_interface_id = child_hash["#{d[":param"]}"].to_i
          pa.save!
        end
      end
    end

    #根据录制的过程和输入参数返回结果
    def get_result
      return "demand id 缺失！" if params[:id].nil?
      demand = Demand.find(params[:id])
      return "demand不存在！" if demand.nil?
      trunk = Interface.find(demand.interface_id)
      return "接口(id:#{demand.interface_id})不存在！" if trunk.nil?
      get_interface_result(trunk.id, params[:id])
    end

    #根据已知接口返回最终结果
    def get_interface_result iid, did
      trunk = Interface.find(iid)
      url = trunk.host
      ps = trunk.param.split(/\s+/)
      ps.each do |p|
        url += "&" if url.include?("=")
        url += "#{p}="
        branch = Param.find_by_interface_id_and_name(trunk.id,p)
        branch = Param.find_by_demand_id_and_name(did,p) if branch.nil?
        if branch.nil?
          return "参数(did:#{did} name:#{p})不存在！"
        else
          if branch.kind == 0
            url += params[p.to_sym]
          else
            url += get_interface_result(branch.children_interface_id,did)   
          end
        end
      end
      keys = trunk.result.split(/\s+/)
      puts "url info :#{url}"
      results = JsonUtil.get_results(keys,url)
      results.join()
    end

end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/views/demands/_form.html.erb
<%= form_for(@demand) do |f| %>
  <% if @demand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demand.errors.count, "error") %> prohibited this demand from being saved:</h2>

      <ul>
      <% @demand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interface_id %><br />
    <%= f.number_field :interface_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demands/edit.html.erb
<%= form_tag url_for(:controller => "builder", :action => "rebuild"), :remote => "true", :class => "form-horizontal" do %>
  <fieldset>
    <legend>查询结果</legend>
    <!--%= text_area_tag "token",flash[:notice],:rows => 25%-->
    <div class="alert alert-success">
      <a class="close" href="<%= demands_path %>" data-dismiss="alert">×</a>
      <%= @result %>
    </div>
  </fieldset>
<% end %>

app/views/demands/index.html.erb
<h3>Listing demands</h3>

<table class="table">
<% @demands.each do |demand| %>
  <tr>
    <td><%= demand.interface_id %></td>
    <td><%= demand.title %></td>
    <td><%= link_to 'Show', demand %></td>
    <td><%= link_to 'Destroy', demand, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Demand', new_demand_path %>

app/views/demands/new.html.erb
<%- model_class = @demand.class -%>
<h1>Demand Add</h1>

<%= form_tag url_for(:controller => "demands", :action => "create"), :class => 'form-horizontal' do %>
  <% if flash[:notice]%>
    <div class="alert alert-error">
      <%= flash[:notice] %> 
    </div>
  <% end %>
  <div class="control-group">
    <%= label_tag "", "Description", :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag :title, "", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag "", "Host", :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag "demand[][:host]", "", :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= label_tag "", "Results", :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag "demand[][:result]", "", :class => 'input-small', :placeholder => '目标结果key' %>
    </div>
  </div>

  <%= hidden_field_tag "demand[][:parent]", "" %>
  
  <div class="control-group">
     <%= label_tag "", "Params", :class => 'control-label' %> <a id="demand_param_add" href="#">+</a>
    <div class="controls">
      <%= text_field_tag "demand[][:param]", "", :class => "input-small" %>
      <%= select_tag "demand[][:type]", options_for_select([["手输","0"], ["接口", "1"]]), :class => "span1", :style => "display:none" %>
    </div>
  </div>


  <div class="form-actions">
    <%= submit_tag nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                demands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/demands/show.html.erb
<%= form_tag demand_path, :method => :put, :class => "form-horizontal" do %>
  <fieldset>
    <legend><%= @demand.title %></legend>
  <% if flash[:notice]%>
    <div class="alert alert-error">
      <%= flash[:notice] %> 
    </div>
  <% end %>
    <% @all_params.each do |p| %>
      <div class="control-group">
        <label class="control-label" for="input01"><%= p %></label>
        <div class="controls">
          <%= text_field_tag "#{p}", "" %>
        </div>
      </div>
    <% end %>

    <div class="form-actions">
    <button class="btn btn-primary" type="submit">确定</button>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), demands_path, :class => "btn" %>
    </div>
  </fieldset>
<% end %>